variable: "variable0"
binning: "bin0=[200,220,250,280,310,340,370,400,430,470,510,550,590,640,690,740,790,840,900,960,1020]"
selections:
    met_shape: "True"
shape: True
regions:
    - "monojet"
    - "singlemu"
    - "doublemu"
    - "singlee"
    - "doublee"
    - "monojetqcd"
    - "singlemuqcd"
    - "singleeqcd"
processes:
    znunu:     0
    dymumu:    1
    zmumu:     2
    gmumu:     3
    dyee:      4
    zee:       5
    gee:       6
    wlnu:      7
    qcd:       8
    wlnu_qcd:  9
    bkg:       10
conversions:
    data_sr:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "Monojet", "MET"]]
        new_labels: [["MET", "monojet", "data_obs"]]
    znunu_sr:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "Monojet", "ZJetsToNuNu"]]
        new_labels: [["MET", "monojet", "znunu"]]
    wlnu_sr:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "Monojet", "WJetsToENu"],
                     ["MET", "Monojet", "WJetsToMuNu"],
                     ["MET", "Monojet", "WJetsToTauNu"]]
        new_labels: [["MET", "monojet", "wlnu"]]
    qcd_sr:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "Monojet", "QCD"]]
        new_labels: [["MET", "monojet", "qcd"]]
    bkg_sr:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "Monojet", "TTJets"],
                     ["MET", "Monojet", "Diboson"],
                     ["MET", "Monojet", "EWKV2Jets"],
                     ["MET", "Monojet", "SingleTop"],
                     ["MET", "Monojet", "G1Jet"],
                     ["MET", "Monojet", "VGamma"],
                     ["MET", "Monojet", "DYJetsToTauTau"]]
        new_labels: [["MET", "monojet", "bkg"]]
    data_mu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuon", "MET"]]
        new_labels: [["MET", "singlemu", "data_obs"]]
    wlnu_mu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuon", "WJetsToENu"],
                     ["MET", "SingleMuon", "WJetsToMuNu"],
                     ["MET", "SingleMuon", "WJetsToTauNu"]]
        new_labels: [["MET", "singlemu", "wlnu"]]
    qcd_mu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuon", "QCD"]]
        new_labels: [["MET", "singlemu", "qcd"]]
    bkg_mu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuon", "TTJets"],
                     ["MET", "SingleMuon", "Diboson"],
                     ["MET", "SingleMuon", "EWKV2Jets"],
                     ["MET", "SingleMuon", "SingleTop"],
                     ["MET", "SingleMuon", "G1Jet"],
                     ["MET", "SingleMuon", "VGamma"],
                     ["MET", "SingleMuon", "DYJetsToTauTau"]]
        new_labels: [["MET", "singlemu", "bkg"]]
    data_mumu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "DoubleMuon", "MET"]]
        new_labels: [["MET", "doublemu", "data_obs"]]
    zmumu_mumu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "DoubleMuon", "DYJetsToMuMu"]]
        new_labels: [["MET", "doublemu", "zmumu"],
                     ["MET", "doublemu", "gmumu"],
                     ["MET", "doublemu", "dymumu"]]
    bkg_mumu:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "DoubleMuon", "TTJets"],
                     ["MET", "DoubleMuon", "Diboson"],
                     ["MET", "DoubleMuon", "EWKV2Jets"],
                     ["MET", "DoubleMuon", "SingleTop"],
                     ["MET", "DoubleMuon", "G1Jet"],
                     ["MET", "DoubleMuon", "VGamma"],
                     ["MET", "DoubleMuon", "DYJetsToTauTau"]]
        new_labels: [["MET", "doublemu", "bkg"]]
    data_e:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectron", "SingleElectron"]]
        new_labels: [["SingleElectron", "singlee", "data_obs"]]
    wlnu_e:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectron", "WJetsToENu"],
                     ["SingleElectron", "SingleElectron", "WJetsToMuNu"],
                     ["SingleElectron", "SingleElectron", "WJetsToTauNu"]]
        new_labels: [["SingleElectron", "singlee", "wlnu"]]
    qcd_e:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectron", "QCD"]]
        new_labels: [["SingleElectron", "singlee", "qcd"]]
    bkg_e:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectron", "TTJets"],
                     ["SingleElectron", "SingleElectron", "Diboson"],
                     ["SingleElectron", "SingleElectron", "EWKV2Jets"],
                     ["SingleElectron", "SingleElectron", "SingleTop"],
                     ["SingleElectron", "SingleElectron", "G1Jet"],
                     ["SingleElectron", "SingleElectron", "VGamma"],
                     ["SingleElectron", "SingleElectron", "DYJetsToTauTau"]]
        new_labels: [["SingleElectron", "singlee", "bkg"]]
    data_ee:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "DoubleElectron", "SingleElectron"]]
        new_labels: [["SingleElectron", "doublee", "data_obs"]]
    zee_ee:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "DoubleElectron", "DYJetsToEE"]]
        new_labels: [["SingleElectron", "doublee", "zee"],
                     ["SingleElectron", "doublee", "gee"],
                     ["SingleElectron", "doublee", "dyee"]]
    bkg_ee:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "DoubleElectron", "TTJets"],
                     ["SingleElectron", "DoubleElectron", "Diboson"],
                     ["SingleElectron", "DoubleElectron", "EWKV2Jets"],
                     ["SingleElectron", "DoubleElectron", "SingleTop"],
                     ["SingleElectron", "DoubleElectron", "G1Jet"],
                     ["SingleElectron", "DoubleElectron", "VGamma"],
                     ["SingleElectron", "DoubleElectron", "DYJetsToTauTau"]]
        new_labels: [["SingleElectron", "doublee", "bkg"]]
    data_qcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "MonojetQCD", "MET"]]
        new_labels: [["MET", "monojetqcd", "data_obs"]]
    qcd_qcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "MonojetQCD", "QCD"]]
        new_labels: [["MET", "monojetqcd", "qcd"]]
    znunu_qcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "MonojetQCD", "ZJetsToNuNu"]]
        new_labels: [["MET", "monojetqcd", "znunu"]]
    wlnu_qcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "MonojetQCD", "WJetsToENu"],
                     ["MET", "MonojetQCD", "WJetsToMuNu"],
                     ["MET", "MonojetQCD", "WJetsToTauNu"]]
        new_labels: [["MET", "monojetqcd", "wlnu_qcd"]]
    bkg_qcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "MonojetQCD", "TTJets"],
                     ["MET", "MonojetQCD", "Diboson"],
                     ["MET", "MonojetQCD", "EWKV2Jets"],
                     ["MET", "MonojetQCD", "SingleTop"],
                     ["MET", "MonojetQCD", "G1Jet"],
                     ["MET", "MonojetQCD", "VGamma"],
                     ["MET", "MonojetQCD", "DYJetsToTauTau"]]
        new_labels: [["MET", "monojetqcd", "bkg"]]
    data_muqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuonQCD", "MET"]]
        new_labels: [["MET", "singlemuqcd", "data_obs"]]
    wlnu_muqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuonQCD", "WJetsToENu"],
                     ["MET", "SingleMuonQCD", "WJetsToMuNu"],
                     ["MET", "SingleMuonQCD", "WJetsToTauNu"]]
        new_labels: [["MET", "singlemuqcd", "wlnu_qcd"]]
    bkg_muqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["MET", "SingleMuonQCD", "TTJets"],
                     ["MET", "SingleMuonQCD", "Diboson"],
                     ["MET", "SingleMuonQCD", "EWKV2Jets"],
                     ["MET", "SingleMuonQCD", "SingleTop"],
                     ["MET", "SingleMuonQCD", "G1Jet"],
                     ["MET", "SingleMuonQCD", "VGamma"],
                     ["MET", "SingleMuonQCD", "DYJetsToTauTau"]]
        new_labels: [["MET", "singlemuqcd", "bkg"]]
    data_eqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectronQCD", "SingleElectron"]]
        new_labels: [["SingleElectron", "singleeqcd", "data_obs"]]
    wlnu_eqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectronQCD", "WJetsToENu"],
                     ["SingleElectron", "SingleElectronQCD", "WJetsToMuNu"],
                     ["SingleElectron", "SingleElectronQCD", "WJetsToTauNu"]]
        new_labels: [["SingleElectron", "singleeqcd", "wlnu_qcd"]]
    bkg_eqcd:
        labels: ["dataset", "region", "process"]
        old_labels: [["SingleElectron", "SingleElectronQCD", "TTJets"],
                     ["SingleElectron", "SingleElectronQCD", "Diboson"],
                     ["SingleElectron", "SingleElectronQCD", "EWKV2Jets"],
                     ["SingleElectron", "SingleElectronQCD", "SingleTop"],
                     ["SingleElectron", "SingleElectronQCD", "G1Jet"],
                     ["SingleElectron", "SingleElectronQCD", "VGamma"],
                     ["SingleElectron", "SingleElectronQCD", "DYJetsToTauTau"]]
        new_labels: [["SingleElectron", "singleeqcd", "bkg"]]
parameters:
    - ["kzll_mcstat", "param", "0", "1"]
    - ["kgll_mcstat", "param", "0", "1"]
    - ["kzmumu", "rateParam", "*", "zmumu", "1.0164589*(1+0.025340129*(@0<0)-0.005476561*(@0>=0))**(@0)*(1+0.001696478*(@1<0)-0.000764713*(@1>=0))**(@1)*(1+0.00081649300)**(@2)",  "lhePdf,lheScale,kzll_mcstat"]
    - ["kzee",   "rateParam", "*", "zee",   "1.0164589*(1+0.025340129*(@0<0)-0.005476561*(@0>=0))**(@0)*(1+0.001696478*(@1<0)-0.000764713*(@1>=0))**(@1)*(1+0.00081649300)**(@2)",  "lhePdf,lheScale,kzll_mcstat"]
    - ["kgll",   "rateParam", "*", "g*",    "0.015040019*(1+0.009749389*(@0<0)-0.005555179*(@0>=0))**(@0)*(1-0.001761234*(@1<0)+0.001456315*(@1>=0))**(@1)*(1+0.0014868245)**(@2)", "lhePdf,lheScale,kgll_mcstat"]
    - ["rw",       "rateParam", "*", "wlnu",     "1",             "[0.1,2.0]"]
    - ["rz",       "rateParam", "*", "znunu",    "1",             "[0.1,2.0]"]
    - ["rz_dy",    "rateParam", "*", "dy*",      "sqrt(@0)",      "rz"]
    - ["rz_zmumu", "rateParam", "*", "zmumu",    "(@0-sqrt(@0))", "rz"]
    - ["rz_zee",   "rateParam", "*", "zee",      "(@0-sqrt(@0))", "rz"]
    - ["rz_gstar", "rateParam", "*", "g*",       "(1-sqrt(@0))",  "rz"]
    - ["rqcd",     "rateParam", "*", "qcd",      "1",             "[0.1,2.0]"]
    - ["rw_qcd",   "rateParam", "*", "wlnu_qcd", "1",             "[0.1,2.0]"]
    - ["*", "autoMCStats", "10", "1"]
systematics:
    - "lumi"
    - "d1k_qcd"
    - "d2k_qcd"
    - "d3k_qcd"
    - "d1k_ew"
    - "d2k_ew_w"
    - "d2k_ew_z"
    - "d3k_ew_w"
    - "d3k_ew_z"
    - "dk_mix"
    - "lhePdf"
    - "lheScale"
    - "metTrigStat"
    - "metTrigSyst"
    - "muonId"
    - "muonIso"
    - "muonTrack"
    - "pileup"
    - "jesAbsoluteStat"
    - "jesAbsoluteScale"
    - "jesAbsoluteMPFBias"
    - "jesFragmentation"
    - "jesSinglePionECAL"
    - "jesSinglePionHCAL"
    - "jesFlavorQCD"
    - "jesTimePtEta"
    - "jesRelativeJEREC1"
    - "jesRelativeJEREC2"
    - "jesRelativeJERHF"
    - "jesRelativePtBB"
    - "jesRelativePtEC1"
    - "jesRelativePtEC2"
    - "jesRelativePtHF"
    - "jesRelativeBal"
    - "jesRelativeFSR"
    - "jesRelativeStatFSR"
    - "jesRelativeStatEC"
    - "jesRelativeStatHF"
    - "jesPileUpDataMC"
    - "jesPileUpPtRef"
    - "jesPileUpPtBB"
    - "jesPileUpPtEC1"
    - "jesPileUpPtEC2"
    - "jesPileUpPtHF"
    - "jesTotal"
    - "jer"
    - "unclust"
    - "eleIdIso"
    - "eleReco"
    - "eleTrig"
