sample_colours:
    MET:              "black"
    SingleMuon:       "black"
    SingleElectron:   "black"
    ZJetsToNuNu:      "#80b1d3"
    WJetsToLNu:       "#b3de69"
    WJetsToENu:       "#b2df8a"
    WJetsToMuNu:      "#b3de69"
    WJetsToTauLNu:    "#8dd3c7"
    WJetsToTauHNu:    "#8dd3c7"
    Diboson:          "#fdb462"
    DYJetsToLL:       "#ffed6f"
    DYJetsToEE:       "#fff6b3"
    DYJetsToMuMu:     "#ffed6f"
    DYJetsToTauTau:   "#ffe41a"
    DYJetsToTauLTauL: "#ffe41a"
    DYJetsToTauLTauH: "#ffe41a"
    DYJetsToTauHTauH: "#ffe41a"
    EWKV2Jets:        "#bebada"
    SingleTop:        "#fccde5"
    TTJets:           "#bc80bd"
    QCD:              "#fb8072"
    G1Jet:            "#ccebc5"
    VGamma:           "#ffffb3"
    Minor:            "#d9d9d9"
sample_names:
    MET:              "MET"
    SingleMuon:       "Single Muon"
    SingleElectron:   "Single Electron"
    ZJetsToNuNu:      "$Z_{\\nu\\nu}$+jets"
    WJetsToLNu:       "$W_{l\\nu}$+jets"
    WJetsToENu:       "$W_{e\\nu}$+jets"
    WJetsToMuNu:      "$W_{\\mu\\nu}$+jets"
    WJetsToTauLNu:    "$W_{\\tau_{l}\\nu}$+jets"
    WJetsToTauHNu:    "$W_{\\tau_{h}\\nu}$+jets"
    Diboson:          "Diboson"
    DYJetsToLL:       "$Z/\\gamma^{*}_{ll}$+jets"
    DYJetsToEE:       "$Z/\\gamma^{*}_{ee}$+jets"
    DYJetsToMuMu:     "$Z/\\gamma^{*}_{\\mu\\mu}$+jets"
    DYJetsToTauTau:   "$Z/\\gamma^{*}_{\\tau\\tau}$+jets"
    DYJetsToTauLTauL: "$Z/\\gamma^{*}_{\\tau_{l}\\tau_{l}}$+jets"
    DYJetsToTauLTauH: "$Z/\\gamma^{*}_{\\tau_{l}\\tau_{h}}$+jets"
    DYJetsToTauHTauH: "$Z/\\gamma^{*}_{\\tau_{h}\\tau_{h}}$+jets"
    EWKV2Jets:        "VBS"
    SingleTop:        "Single Top"
    TTJets:           "$t\\bar{t}$+jets"
    QCD:              "Multijet"
    G1Jet:            "$\\gamma$+jets"
    VGamma:           "$V+\\gamma$"
    Minor:            "Minors"
axis_label:
    METnoX_pt:  "$p_{\\mathrm{T}}^{\\mathrm{miss}}$ (GeV)"
    METnoX_phi: "$p_{\\mathrm{T}}^{\\mathrm{miss}}\\ \\phi$"
    MET_pt:  "$p_{\\mathrm{T,PF}}^{\\mathrm{miss}}$ (GeV)"
    MET_phi: "$p_{\\mathrm{T,PF}}^{\\mathrm{miss}}\\ \\phi$"
    CaloMET_pt:  "$p_{\\mathrm{T,calo}}^{\\mathrm{miss}}$ (GeV)"
    CaloMET_phi: "$p_{\\mathrm{T,calo}}^{\\mathrm{miss}}\\ \\phi$"
    MET_dCaloMET: "$|p_{\\mathrm{T,PF}}^{\\mathrm{miss}} - p_{\\mathrm{T,calo}}^{\\mathrm{miss}}| / p_{\\mathrm{T}}^{\\mathrm{miss}}$ (GeV)"
    MinDPhiJ1234METnoX: "$\\mathrm{min}\\Delta\\phi(j_{0,1,2,3}, p_{\\mathrm{T}}^{\\mathrm{miss}})$"
    MTW: "$m_{\\mathrm{T}}(\\ell, p_{\\mathrm{T}}^{\\mathrm{miss}})$ (GeV)"
    MLL: "$m_{\\ell,\\ell}$ (GeV)"
    nJetVeto: "Jet veto multiplicity"
    nJetSelection: "Jet selection multiplicity"
    LeadJetSelection_pt: "$p_{\\mathrm{T}}(j_0)$ (GeV)"
    LeadJetSelection_eta: "$\\eta(j_0)$"
    LeadJetSelection_phi: "$\\phi(j_0)$"
    LeadJetSelection_chHEF: "$\\mathrm{Ch.\\ Had.\\ EF}(j_0)$"
    SecondJetSelection_pt: "$p_{\\mathrm{T}}(j_1)$ (GeV)"
    SecondJetSelection_eta: "$\\eta(j_1)$"
    SecondJetSelection_phi: "$\\phi(j_1)$"
    nMuonVeto: "Muon veto multiplicity"
    nMuonSelection: "Muon selection multiplicity"
    LeadMuonSelection_pt: "$p_{\\mathrm{T}}(\\mu_0)$ (GeV)"
    LeadMuonSelection_eta: "$\\eta(\\mu_0)$"
    LeadMuonSelection_phi: "$\\phi(\\mu_0)$"
    SecondMuonSelection_pt: "$p_{\\mathrm{T}}(\\mu_1)$ (GeV)"
    SecondMuonSelection_eta: "$\\eta(\\mu_1)$"
    SecondMuonSelection_phi: "$\\phi(\\mu_1)$"
    nElectronVeto: "Electron veto multiplicity"
    nElectronSelection: "Electron selection multiplicity"
    LeadElectronSelection_pt: "$p_{\\mathrm{T}}(e_0)$ (GeV)"
    LeadElectronSelection_eta: "$\\eta(e_0)$"
    LeadElectronSelection_phi: "$\\phi(e_0)$"
    SecondElectronSelection_pt: "$p_{\\mathrm{T}}(e_1)$ (GeV)"
    SecondElectronSelection_eta: "$\\eta(e_1)$"
    SecondElectronSelection_phi: "$\\phi(e_1)$"
    nTauVeto: "Tau veto multiplicity"
    nTauSelection: "Tau selection multiplicity"
    LeadTauSelection_pt: "$p_{\\mathrm{T}}(\\tau_0)$ (GeV)"
    LeadTauSelection_eta: "$\\eta(\\tau_0)$"
    LeadTauSelection_phi: "$\\phi(\\tau_0)$"
    SecondTauSelection_pt: "$p_{\\mathrm{T}}(\\tau_1)$ (GeV)"
    SecondTauSelection_eta: "$\\eta(\\tau_1)$"
    SecondTauSelection_phi: "$\\phi(\\tau_1)$"
    nPhotonVeto: "Photon veto multiplicity"
    nPhotonSelection: "Photon selection multiplicity"
    nBJetVeto: "B-tagged jet veto multiplicity"
    PV_npvsGood: "Good PV multiplicity"
